[sdl]
fullscreen=false
windowresolution=original

[autoexec]
# 掛載 Lab2 的程式碼資料夾為 C 槽
mount c c:\NYCU\embedded_real_time\RTOS_LAB\RTOS_Lab2\Lab2_code
c:
cd \SOFTWARE\uCOS-II\Lab2\BC45\TEST

# 清除舊的編譯檔並重新編譯
del ..\OBJ\*.OBJ 
MAKETEST.BAT

# 執行編譯出來的程式（結果顯示在螢幕上，按任意鍵後退出）
TEST.EXE
exit
