[sdl]
fullscreen=false
windowresolution=original

[autoexec]
mount c c:\NYCU\embedded_real_time\RTOS_LAB\RTOS_Lab2\Lab2_code
c:
cd \SOFTWARE\uCOS-II\Lab2\BC45\TEST
del ..\OBJ\*.OBJ
CALL MAKETEST.BAT
TEST.EXE > out_set1.txt
exit
